name: CI Build Push and Deploy

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ci-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set image tag
      run: |
        VERSION=$(grep VERSION app.py | cut -d '"' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ env.VERSION }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ env.VERSION }} \
                   ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
